version: '3.5'

services:

  aspace-pui-tests:
    container_name: 'aspace-pui-tests'
    build:
      context: './'
      dockerfile: './Dockerfile'
    env_file:
      - '.env'
    networks:
        - aspace-local

  
networks:
  aspace-local:
      name: aspace-local
